INSERT INTO USERS
(LOGIN, PASSWORD, ROLE, IS_ACTIVE)
VALUES
    ('Bogdankosyanenko@icloud.com','28085678','ADMIN',TRUE);

INSERT INTO USERS
(LOGIN, PASSWORD, ROLE, IS_ACTIVE)
VALUES
    ('emirmus69@gmail.com','12345678','USER',FALSE);