INSERT INTO USER_ENTITY
(LOGIN, PASSWORD, ROLE, IS_ACTIVE)
VALUES
    ('Bogdan@icloud.com','28085678','ADMIN',TRUE);

INSERT INTO USER_ENTITY
(LOGIN, PASSWORD, ROLE, IS_ACTIVE)
VALUES
    ('David@gmail.com','12345678','USER',FALSE);