CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE TODO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    COMPLETED BOOLEAN NOT NULL

);

CREATE TABLE AUTHORS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    AUTHORS VARCHAR(40) NOT NULL
);

CREATE TABLE STATUS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN

);