ALTER TABLE TODO
RENAME COLUMN TITLE TO TEXT;

ALTER TABLE TODO
RENAME COLUMN COMPLETED TO STATUS;

ALTER TABLE TODO
ADD COLUMN CREATED_AT TIMESTAMP;

ALTER TABLE  TODO
ADD COLUMN UPDATED_AT TIMESTAMP;

ALTER TABLE TODO
ADD COLUMN IS_VISIBLE BOOLEAN;

ALTER TABLE TODO
ADD COLUMN AUTHOR VARCHAR(40);

ALTER TABLE TODO
DROP COLUMN USER_ID;

