ALTER TABLE TODO_ENTITY
RENAME COLUMN TITLE TO TEXT;

ALTER TABLE TODO_ENTITY
RENAME COLUMN COMPLETED TO STATUS;

ALTER TABLE TODO_ENTITY
ADD COLUMN CREATED_AT TIMESTAMP;

ALTER TABLE  TODO_ENTITY
ADD COLUMN UPDATED_AT TIMESTAMP;

ALTER TABLE TODO_ENTITY
ADD COLUMN IS_VISIBLE BOOLEAN;

ALTER TABLE TODO_ENTITY
ADD COLUMN AUTHOR VARCHAR(40);

ALTER TABLE TODO_ENTITY
DROP COLUMN USER_ID;

