ALTER TABLE TODO_ENTITY
DROP COLUMN AUTHOR;

ALTER TABLE TODO_ENTITY
DROP COLUMN STATUS;

ALTER TABLE TODO_ENTITY
ADD COLUMN AUTHOR_ID INT;

ALTER TABLE TODO_ENTITY
ADD COLUMN STATUS_ID INT;

ALTER TABLE TODO_ENTITY
ADD FOREIGN KEY (AUTHOR_ID)
REFERENCES AUTHOR_ENTITY(ID);

ALTER TABLE TODO_ENTITY
ADD FOREIGN KEY (STATUS_ID)
REFERENCES STATUS_ENTITY(ID);