ALTER TABLE TODO
DROP COLUMN AUTHOR;

ALTER TABLE TODO
DROP COLUMN STATUS;

ALTER TABLE TODO
ADD COLUMN AUTHOR_ID INT;

ALTER TABLE TODO
ADD COLUMN STATUS_ID INT;

ALTER TABLE TODO
ADD FOREIGN KEY (AUTHOR_ID)
REFERENCES AUTHORS(ID);

ALTER TABLE TODO
ADD FOREIGN KEY (STATUS_ID)
REFERENCES STATUS(ID);