DROP VIEW IF EXISTS TODO_VIEW;

CREATE VIEW TODO_VIEW AS
SELECT
    t.ID,
    t.TEXT,
    t.AUTHOR_ID,
    t.STATUS_ID,
    t.CREATED_AT,
    t.UPDATED_AT,
    t.IS_VISIBLE,
    a.AUTHORS AS AUTHOR_NAME,
    s.STATUS AS STATUS_NAME
FROM TODO t
         JOIN AUTHORS a
              ON t.AUTHOR_ID = a.ID
         JOIN STATUS s
              ON t.STATUS_ID = s.ID;